name: Authorization CI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/Altinn.Platform/Altinn.Platform.Authorization/Authorization/**'    

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Authz container
        id: build_authz
        uses: docker/build-push-action@v2
          with:
            platforms: linux/arm64
            context: src/Altinn.Platform/Altinn.Platform.Authorization
            file: src/Altinn.Platform/Altinn.Platform.Authorization/Authorization/Dockerfile
            

        
        
