name: Receipt CI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/Altinn.Platform/Altinn.Platform.Receipt/Receipt/**'    

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build Receipt container
        id: build_receipt
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64,linux/amd64
          context: ./
          file: src/Altinn.Platform/Altinn.Platform.Receipt/Receipt/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/altinn-receipt:latest
